import { systemWeights } from 'react-native-typography';
import palettes from './palettes';
import { createTheme, DefaultTheme } from '@draftbit/ui';
export default createTheme({
  breakpoints: {},
  palettes,
  baseTheme: DefaultTheme,
  theme: {
    name: 'Rentbit Theme',
    colors: {
      background: {
        base: {
          default: palettes.Brand.Background,
          dark: palettes.Rentbit['Custom Color'],
        },
        brand: {
          default: palettes.Brand.Background,
          dark: palettes.Gray[700],
        },
        danger: palettes.Brand.Error,
      },
      border: {
        base: palettes.Brand.Divider,
        brand: palettes.Brand.Divider,
        danger: palettes.Brand.Error,
      },
      branding: {
        primary: {
          default: palettes.Amber[500],
          dark: palettes.Orange[500],
        },
        secondary: {
          default: palettes.Lime[400],
          dark: palettes.Lime[500],
        },
      },
      foreground: {
        base: palettes.Brand.Light,
        brand: palettes.Brand.Light,
        danger: palettes.Brand.Light,
      },
      text: {
        danger: {
          default: palettes.Rentbit.Darker_Pink,
          dark: palettes.Brand.Error,
        },
        light: {
          default: palettes.Brand.Light,
          dark: palettes.Brand['Light Inverse'],
        },
        medium: {
          default: palettes.Brand.Medium,
          dark: palettes.Brand['Medium Inverse'],
        },
        strong: {
          default: palettes.Brand.Strong,
          dark: palettes.Brand['Strong Inverse'],
        },
      },
    },
    typography: {
      body1: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 15,
        lineHeight: 26,
        letterSpacing: 0,
        fontFamily: 'Poppins_400Regular',
      },
      body2: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 22,
        letterSpacing: 0,
        fontFamily: 'Poppins_400Regular',
      },
      button: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 15,
        lineHeight: 16,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      caption: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 16,
        letterSpacing: 0,
        fontFamily: 'System_400Regular',
      },
      headline1: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 60,
        lineHeight: 71,
        letterSpacing: 0,
        fontFamily: 'Poppins_400Regular',
      },
      headline2: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 48,
        lineHeight: 58,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      headline3: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 40,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      headline4: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      headline5: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      headline6: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      overline: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 2,
        fontFamily: 'Poppins_400Regular',
      },
      subtitle1: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 15,
        lineHeight: 26,
        letterSpacing: 0,
        fontFamily: 'Poppins_400Regular',
      },
      subtitle2: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 22,
        letterSpacing: 0,
        fontFamily: 'System_400Regular',
      },
      custom14: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 36,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom15: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 36,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom16: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'WorkSans_400Regular',
      },
      custom17: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Merriweather_400Regular_Italic',
      },
      custom18: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.bold ?? {}),
        fontWeight: '700',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Merriweather_700Bold_Italic',
      },
      custom19: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom20: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom21: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 26,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom22: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom23: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.bold ?? {}),
        fontWeight: '700',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_700Bold',
      },
      custom24: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.bold ?? {}),
        fontWeight: '700',
        fontSize: 24,
        lineHeight: 46,
        letterSpacing: 0,
        fontFamily: 'Poppins_700Bold',
      },
      custom25: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 22,
        letterSpacing: 0,
        fontFamily: 'Poppins_400Regular',
      },
      custom26: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 16,
        letterSpacing: 0,
        fontFamily: 'System_400Regular',
      },
      custom27: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.regular ?? {}),
        fontWeight: '400',
        fontSize: 13,
        lineHeight: 16,
        letterSpacing: 0,
        fontFamily: 'System_400Regular',
      },
      custom28: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 32,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom29: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 32,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom30: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 24,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom31: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 48,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom32: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 48,
        letterSpacing: 0,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom33: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 16,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom34: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 16,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom35: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 16,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom36: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom37: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom38: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
      custom39: {
        ...(({ backgroundColor, ...o }) => o)(systemWeights.semibold ?? {}),
        fontWeight: '600',
        fontSize: 24,
        lineHeight: 16,
        letterSpacing: 1,
        fontFamily: 'Poppins_600SemiBold',
      },
    },
  },
});
